### ISSUE TITLE
sess_file_rewrite() calls cgi_init_headers()

### ISSUE THREAD

**Issue by LeSpocky** [rafaelsteil/libcgi#19]
While working with sessions and using `cgi_session_alter_var()` before `cgi_redirect()` I noticed the former calling `sess_file_rewrite()` which seems plausible. However `sess_file_rewrite()` calls `cgi_init_headers()` for no obvious reason leading to `cgi_redirect()` complaining about already initialized headers.

I suggest removing the `cgit_init_headers()` call, but I'm not entirely sure if this would have some side effects I could not see?!

**Comment by rafaelsteil** [comment]
Seems odd to me as well. It only writes to the filesystem, there isn't any
reason to init the cgi hreaders there.
